#!/usr/bin/env bash
set -e

name=$(basename `pwd`)

python3 -m venv .venv-"$name"
ln -s .venv-"$name"/bin/activate activate
source activate
pip install --upgrade pip
pip install -r requirements.txt
pip install -r requirements-dev.txt
python setup.py develop
