#!/usr/bin/env bash
set -e

python3 -m venv .venv
ln -s .venv/bin/activate activate
source activate
pip install --upgrade pip
pip install -r requirements.txt
pip install -r requirements-dev.txt
python setup.py develop
